apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Base64 String: superman@yopmail.com = c3VwZXJtYW5AeW9wbWFpbC5jb20=
  # echo -n superman@yopmail.com | base64
  JWT_SECRET: c3VwZXJtYW5AeW9wbWFpbC5jb20=
