apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # Base64 String: postgres = cG9zdGdyZXM=
  # echo -n postgres | base64
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=